#!/bin/bash

#Sys Tray
#trayer --widthtype percent --heighttype pixel --width 5 --height 14 --edge top --align right --tint 0x000000 --transparent true &

#Dropbox
#dropboxd &

#Wallpaper
nitrogen --restore &

#Notif Daemon
dunst -config ~/.dunstrc


